version: "3.6"

services:
  web:
    image: node:20.10
    ports:
      - 3000:3000
    volumes:
      - ./web:/web
    working_dir: /web
    restart: always
    command: npm run dev

  api:
    image: golang:1.20
    ports:
      - 8000:8000
    volumes:
      - ./api:/go/src/api
    working_dir: /go/src/api
    network_mode: host
    restart: always
    depends_on:
      - db
    command: go run cmd/api/main.go

  db:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gorm
      - POSTGRES_PASSWORD=gorm
      - POSTGRES_DB=gorm
    restart: always

  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
