import type { Metadata } from "next";
import { ChakraProvider } from "@chakra-ui/react";
import { theme } from "@/styles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <ChakraProvider cssVarsRoot="body" theme={theme}>
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
