name: Deploy api to ghcr.io

on:
  push:
    branches:
      - master
    paths:
      - api/**
      - .github/workflows/deploy_api.yml

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: generate .env
        run: |
          touch .env
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_TIMEZONE=${{ secrets.DATABASE_TIMEZONE }}" >> .env

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/centralserver-api:latest
            ghcr.io/${{ github.repository_owner }}/centralserver-api:1.0.0
